image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker

github:
  prebuilds:
    master: true
    branches: true

tasks:
  - name: Setup
    openMode: split-left
    init: |
      make generate
      make build
    command: make start
  - openMode: split-right
    command: |
      gp await-port 8080

ports:
  - port: 8080
    onOpen: ignore
    visibility: public
